name: Send Email on Push to Main

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Githubmail repo updated!"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions
          body: |
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Commit message: ${{ github.event.head_commit.message }}
